openapi: 3.0.3
info:
  title: eIDAS Bridge API
  description: eIDAS Bridge API supplies all the endpoints to sign verifiable credentials with your certificate. Notice that this API is equally authenticated to VIDcredentials. Therefore, in order to perform operations with the eIDAS Bridge, an access token has to be previously obtained by sessions request.
  version: 1.2.8
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://staging.vidchain.net
    description: Validated ID API Docs
tags:
  - name: Authentication Service
    description: Manage User and Legal Entities Authentication
paths:
  /api/v1/sessions:
    post:
      operationId: post-api-v1-sessions
      tags:
        - Authentication Service
      summary: Authenticate your entity
      description: Get your accessToken here. Remember that the access token is a JWT with an expiration time so from time to time you will need to get a new one.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionsRequest"
            examples:
              Entity Session Request:
                $ref: "#/components/examples/EntitySessionRequest"
              User Session Request:
                $ref: "#/components/examples/UserSessionRequest"

        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionsResponse"
              examples:
                Access Token:
                  value:
                    accessToken: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJ2aWRjaGFpbi1hcGkifQ.eyJzdWIiOiJlbnRpdGF0U3dhZ2dlciIsImRpZCI6ImRpZDp2aWQ6MHg5YzZGZjkwMDk2RmFBNDMxRGZBZEQ2MDBDOUI0Qjc4QjE2N2VBNzA1Iiwibm9uY2UiOiJ6LTA0MjdkYzI1MTViMSIsImlhdCI6MTYyMzIzMDIxMiwiZXhwIjoxNjI1ODIyMjEyLCJhdWQiOiJ2aWRjaGFpbi1hcGkifQ.V60YU-lQLEWJoW360ykQWvUpnasLd0ZPTgmeIIh-V_yp6fpZw97TfWLPcd08cKy-QeVmgyLlfL6TxmjPtRukFA
                    tokenType: bearer
                    expiresIn: 900
                    issuedAt: "1622815877"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
                Expired Token:
                  $ref: "#/components/examples/ExpiredToken"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /api/v1/eidas/keys:
    put:
      tags:
        - eIDAS Bridge
      summary: Associate your DID to an eIDAS QEC
      description: Associate your DID with an eIDAS Qualified Electronic Certificate (QEC) to eSeal W3C Verifiable Credentials
      operationId: put-eidas-bridge-v1-eidas-keys
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EidasQecInput"
        required: true
      responses:
        "201":
          description: Keys stored
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EidasQecResponse"
        "200":
          description: Keys updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EidasQecResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /api/v1/eidas/signatures:
    post:
      tags:
        - eIDAS Bridge
      summary: eSeal a Verifiable Credential using your certificate
      description: Request to sign a credential with DID's EIDAS associated keys. It requires providing the DID of the issuer, the payload to sign, the signature type and password to decode P12 file. Create an eIDAS eSeal signature using the associated eIDAS keys with a DID. Notice that you will have to previously associate your issuer did with a valid certificate. Notice that the certificate provided as example is only for test purposes, do not use it for your own certificates.
      operationId: post-eidas-bridge-v1-signatures
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignatureInput"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/verifiableCredentialEsealed"
              examples:
                One Proof EIDAS Signature:
                  value:
                    "@context":
                      - "https://www.w3.org/2018/credentials/v1"
                      - "https://api.vidchain.net/credentials/verifiableId/v1"
                    id: http://example.vid/credentials/1872
                    type: ['VerifiableCredential','VerifiableID']
                    issuer: did:key:z6MkkGj1UZAUjWzrt5zgdhxM4WcZE5bHKZogQKZHvt8hrXzE
                    issuanceDate: "2019-06-22T14:11:44Z"
                    expirationDate: "2019-06-22T14:11:44Z"
                    credentialSubject:
                      id: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
                      firstName: "Eva"
                      lastName: "Monroe"
                      gender: "Female"
                      dateOfBirth: "12/11/1970"
                      placeOfBirth: "Madrid"
                      currentAddress: "Arago 179 4a"
                      city: "Barcelona"
                      state: "Catalunya"
                      zip: "08011"
                    proof:
                      type: "CAdESRSASignature2020"
                      created: "2020-06-22T14:11:44Z"
                      proofPurpose: "assertionMethod"
                      verificationMethod: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
                      cades: 308204c906092a864886f70d010702...266ad9fee3375d8095
                Mutiple Proofs EIDAS Signature:
                  value:
                    "@context":
                      - "https://www.w3.org/2018/credentials/v1"
                      - "https://api.vidchain.net/credentials/verifiableId/v1"
                    id: http://example.vid/credentials/1872
                    type: ['VerifiableCredential','VerifiableID']
                    issuer: did:key:z6MkkGj1UZAUjWzrt5zgdhxM4WcZE5bHKZogQKZHvt8hrXzE
                    issuanceDate: "2019-06-22T14:11:44Z"
                    expirationDate: "2019-06-22T14:11:44Z"
                    credentialSubject:
                      id: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
                      firstName: "Eva"
                      lastName: "Monroe"
                      gender: "Female"
                      dateOfBirth: "12/11/1970"
                      placeOfBirth: "Madrid"
                      currentAddress: "Arago 179 4a"
                      city: "Barcelona"
                      state: "Catalunya"
                      zip: "08011"
                    proof:
                      - type: "EcdsaSecp256k1Signature2019"
                        created: "2019-06-22T14:11:44Z"
                        proofPurpose: "assertionMethod"
                        verificationMethod: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2#keys-1
                        jws: "eyJhbGciOiJFU...pKTV3co3wXAE"
                      - type: "CAdESRSASignature2020"
                        created: "2020-06-22T14:11:44Z"
                        proofPurpose: "assertionMethod"
                        verificationMethod: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
                        cades: 308204c906092a864886f70d010702...266ad9fee3375d8095
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /api/v1/eidas/signature-validations:
    post:
      tags:
        - eIDAS Bridge
      summary: Validate an eSealed Verifiable Credential
      description: Validate a W3C Verifiable Credential eSealed with an eIDAS QEC.
      operationId: post-eidas-bridge-v1-signature-validations
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/esealedCred"
        required: true
      responses:
        "200":
          description: Verification performed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Verification"
              examples:
                TOTAL_PASSED:
                  $ref: "#/components/examples/TotalSuccess"
                TOTAL_FAILED:
                  $ref: "#/components/examples/TotalFailed"
                INDETERMINATE:
                  $ref: "#/components/examples/Indeterminate"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
components:
  schemas:
    SessionsRequest:
      title: Sessions Request
      description: Request for OAuth 2.0 JWT bearer assertion grant.
      type: object
      properties:
        grantType:
          description: 'OAuth 2.0 grant type. Must be set to "urn:ietf:params:oauth:grant-type:jwt-bearer"'
          type: string
          example: "urn:ietf:params:oauth:grant-type:jwt-bearer"
        assertion:
          type: string
          description: JSON encoded in base64. Decode provided example to see the values within.
          example: ewogICAgImlzcyI6ImVudGl0YXRTd2FnZ2VyIiwKICAgImF1ZCI6InZpZGNoYWluLWFwaSIsCiAgICJub25jZSI6InotMDQyN2RjMjUxNWIxIiwKICAgImNhbGxiYWNrVXJsIjoiaHR0cDovLzEyNy4wLjAuMTo4MDgwL2RlbW8vZW50aXRhdC1leGVtcGxlL2NhbGxiYWNrIiwKICAgImFwaUtleSI6ICI2MDAxMGMwZi05MmQ2LTQyMDYtYmFjYi1hMDRhYzA4MGVjNjMiCn0=
        scope:
          type: string
          description: Scope is used to define the authentication method.
          example: vidchain profile entity
        expiresIn:
          type: number
          example: 900
          description: Time in seconds after which the token should not be accepted
      required:
        - grantType
        - assertion
        - scope
    SessionsResponse:
      title: Sessions Response
      type: object
      properties:
        accessToken:
          description: A signed JWT Access Token issued by the vidchain-api to access the API.
          type: string
          example: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJ2aWRjaGFpbi1hcGkifQ.eyJzdWIiOiJlbnRpdGF0RXhlbXBsZSIsImRpZCI6ImVudGl0YXRFeGVtcGxlIiwibm9uY2UiOiJ6LTA0MjdkYzI1MTViMSIsImlhdCI6MTYyMzA1NDcyNywiZXhwIjoxNjI1NjQ2NzI3LCJhdWQiOiJ2aWRjaGFpbi1hcGkifQ.mc7aXMOnLUF8hF0dtDiMamqZAE-iX5xG72qfXobhi_xnOiQb1bvIKOHKRJ2ALUU4XbzP2tGeFSFZaY9ul_jdhg
        tokenType:
          description: 'Type of the authentication token. Supported type "bearer".'
          type: string
          example: Bearer
        expiresIn:
          description: JWT expiration in seconds.
          type: integer
          example: 900
        issuedAt:
          description: "Time of JWT issuance. Format: unix timestamp"
          type: string
          example: "1467841035013"
      description: Authentication JWT
    esealedCred:
      type: object
      description: eSealed Verifiable Credential Data Model
      example:
        "@context":
          - "https://www.w3.org/2018/credentials/v1"
        id: "https://example.com/credential/2390"
        type:
          - VerifiableCredential
          - VerifiableId
        issuer: "did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0"
        issuanceDate: "2022-06-09T12:42:48.000Z"
        credentialSubject:
          birthName: "Eva"
          currentAddress: "44, rue de Fame"
          currentFamilyName: "Eva"
          currentGivenName: "Adams"
          dateOfBirth: "1998-02-14"
          gender: "Female"
          id: "did:ethr:0x2Bb1629Dc1f992E00a9E170464BE3802ba259B3E"
          personIdentifier: "BE/BE/02635542Y"
          placeOfBirth: "Brussels"
        proof:
          - type: "EcdsaSecp256k1Signature2019"
            created: "2022-06-09T12:42:48.000Z"
            proofPurpose: "assertionMethod"
            verificationMethod: "did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0#keys-1"
            jws: "eyJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6ZXRocjoweERmQkE3RTdENmZkOUQzQjVCOTAwY0UyYWEzZDlFNmFBNDM1NzRGQzAja2V5cy0xIiwidHlwIjoiSldUIn0.eyJpYXQiOjE2NTQ3Nzg1NjgsImlzcyI6ImRpZDpldGhyOjB4RGZCQTdFN0Q2ZmQ5RDNCNUI5MDBjRTJhYTNkOUU2YUE0MzU3NEZDMCIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImJpcnRoTmFtZSI6IkV2YSIsImN1cnJlbnRBZGRyZXNzIjoiNDQsIHJ1ZSBkZSBGYW1lIiwiY3VycmVudEZhbWlseU5hbWUiOiJFdmEiLCJjdXJyZW50R2l2ZW5OYW1lIjoiQWRhbXMiLCJkYXRlT2ZCaXJ0aCI6IjE5OTgtMDItMTQiLCJnZW5kZXIiOiJGZW1hbGUiLCJpZCI6ImRpZDpldGhyOjB4MkJiMTYyOURjMWY5OTJFMDBhOUUxNzA0NjRCRTM4MDJiYTI1OUIzRSIsInBlcnNvbklkZW50aWZpZXIiOiJCRS9CRS8wMjYzNTU0MlkiLCJwbGFjZU9mQmlydGgiOiJCcnVzc2VscyJ9LCJpZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20vY3JlZGVudGlhbC8yMzkwIiwiaXNzdWVyIjoiZGlkOmV0aHI6MHhDQzI0MkEzZGNBMzkzNjM4NDc2MDdjOTg5ZDVhMzNDMmY2RDZhMEZmIiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZlcmlmaWFibGVJZCJdfX0.XfY8VdEInTadbUo8MAimW6CbvLWxGgDuMk1W5f24ynCzJaZG8K6MjXDsy16WLjiXonkUwtRTfdnI5k_Oic5U5g"
          - type: "CAdESRSASignature2020"
            created: "2022-06-13T08:31:27Z"
            proofPurpose: "assertionMethod"
            verificationMethod: "did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0#MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5GX6o+OfaZHbeRi3pWpkskkD96MJMmDl1tTS0y693Qv0cxPMd0kaR0MGkRK5tFWL1d+SVb7mxmYGrZuUjbE1B8O2MK8MvoRhQl6NiTmmy9JY9xKZKUT6VUuxlwJTMU732YocPCIJgN2RJ4ZwmG8nyoggDplRi3P3VYhU1LpNjureoJAHS9DIc1OpwgQWq4qpcFkMV3+8/pxbmwawYqNpfxi+j3+qK7wf+u1dj0BGJ2JX9uFbX3Vd+P0HFN0/W0IzdkYUs0/R2K2GbRFxJkuAEWjeJkqAp5CEzbKxlM9y6V9KM8ZNpEAlHvPb/E1HfrmMwP7B1yV2u6B6kwNWSVa7QwIDAQAB"
            cades: "-----BEGIN PKCS7-----MIIH2QYJKoZIhvcNAQcCoIIHyjCCB8YCAQExDzANBglghkgBZQMEAgEFADBPBgkqhkiG9w0BBwGgQgRA47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFXJIgVCHLlR1Lb4Kv8y+C+lwzfaE6cIdCY27j9HOOlogaCCBBcwggQTMIIC+6ADAgECAhQnSFMmzAXkEGt5CBsRAvwVMtfAcDANBgkqhkiG9w0BAQsFADCBmDELMAkGA1UEBhMCTkwxFjAUBgNVBAgMDU5vb3JkLUhvbGxhbmQxEjAQBgNVBAcMCUFtc3RlcmRhbTEUMBIGA1UECgwLVGVzdENvbXBhbnkxCzAJBgNVBAsMAklUMRUwEwYDVQQDDAxTY290dCBNYWxsZXkxIzAhBgkqhkiG9w0BCQEWFHNtYWxsZXlAc3BoZXJlb24uY29tMB4XDTIwMTIwMjE0MzEwNVoXDTMwMTEzMDE0MzEwNVowgZgxCzAJBgNVBAYTAk5MMRYwFAYDVQQIDA1Ob29yZC1Ib2xsYW5kMRIwEAYDVQQHDAlBbXN0ZXJkYW0xFDASBgNVBAoMC1Rlc3RDb21wYW55MQswCQYDVQQLDAJJVDEVMBMGA1UEAwwMU2NvdHQgTWFsbGV5MSMwIQYJKoZIhvcNAQkBFhRzbWFsbGV5QHNwaGVyZW9uLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAORl+qPjn2mR23kYt6VqZLJJA/ejCTJg5dbU0tMuvd0L9HMTzHdJGkdDBpESubRVi9XfklW+5sZmBq2blI2xNQfDtjCvDL6EYUJejYk5psvSWPcSmSlE+lVLsZcCUzFO99mKHDwiCYDdkSeGcJhvJ8qIIA6ZUYtz91WIVNS6TY7q3qCQB0vQyHNTqcIEFquKqXBZDFd/vP6cW5sGsGKjaX8Yvo9/qiu8H/rtXY9ARidiV/bhW191Xfj9BxTdP1tCM3ZGFLNP0dithm0RcSZLgBFo3iZKgKeQhM2ysZTPculfSjPGTaRAJR7z2/xNR365jMD+wdcldrugepMDVklWu0MCAwEAAaNTMFEwHQYDVR0OBBYEFPZvjfNUC6pVbAUhktJNI50jefkgMB8GA1UdIwQYMBaAFPZvjfNUC6pVbAUhktJNI50jefkgMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAGcrKcTfDTgXIQelgmz3h5iu8oCAfqW9q8eUNuJnGrViA/BA3uVsUojJnGx9zHVAa7VGT974HsP6l4hga0vT6VDFsLzyiCHTcJo+qskSGGZLEsQ34vcdCX6ki1VRMofyRrEd4LzrKbak4QlbbLuZW09iSuAyJOOY4mPrSEkRATztVP9MH+ygBc6byhVfLUdrcfAdni+i4b9LBiFdZqqc5QM6J9Hnv0LLnewyS4bSbtK5fE5mnbSOdftNpHwSUfyZmJ9NIGORPZE2PVCEUb5OXmdH9DrePjEjD1/ZKP6NVyWy4hwRCHTRujyl90yED6wxfXMKw68bewOex+youYvuC5UxggNCMIIDPgIBATCBsTCBmDELMAkGA1UEBhMCTkwxFjAUBgNVBAgMDU5vb3JkLUhvbGxhbmQxEjAQBgNVBAcMCUFtc3RlcmRhbTEUMBIGA1UECgwLVGVzdENvbXBhbnkxCzAJBgNVBAsMAklUMRUwEwYDVQQDDAxTY290dCBNYWxsZXkxIzAhBgkqhkiG9w0BCQEWFHNtYWxsZXlAc3BoZXJlb24uY29tAhQnSFMmzAXkEGt5CBsRAvwVMtfAcDANBglghkgBZQMEAgEFAKCCAWEwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjIwNjEzMDgzMTI4WjAvBgkqhkiG9w0BCQQxIgQgW3ebSBjHWslzfAvrKI3LZqmvWmMOhsCadPkPeMPuQb4wgfUGCyqGSIb3DQEJEAIvMYHlMIHiMIHfMIHcBCD3SVjat5f3AQRhEKblwdKspJ3ZS87w3K1LUXSqPg5RPzCBtzCBnqSBmzCBmDELMAkGA1UEBhMCTkwxFjAUBgNVBAgMDU5vb3JkLUhvbGxhbmQxEjAQBgNVBAcMCUFtc3RlcmRhbTEUMBIGA1UECgwLVGVzdENvbXBhbnkxCzAJBgNVBAsMAklUMRUwEwYDVQQDDAxTY290dCBNYWxsZXkxIzAhBgkqhkiG9w0BCQEWFHNtYWxsZXlAc3BoZXJlb24uY29tAhQnSFMmzAXkEGt5CBsRAvwVMtfAcDANBgkqhkiG9w0BAQsFAASCAQCZLICVvpT+XmZYd6+5eBuC+wk/qemwQhBcxnuSaj+DEgL7XSg0LkZl4S3AUm52i8T/C+IWDQFEsMO7o7XFGhkJkodjTQEbt3TjTaoeZbo3yI+m1mujinOtS/Q3lJTQwbe43tDt62gRfKA4sBY9pMRWo0CvnOFr74hCw6AV8DN3l2QY7bCvgXSTQGhbcvOpdrr8FLJTpTr939aLQelcsfXwtdmRNH1/BN8CRo3fJ6FQvIB18Q0eVqoSFoKV62Ix2mr2WQHbC6jAEKjUaWlaKUBwNM0JTrBnNuKT1FRUvb5sUYpPLf7/tzOm45JL4A8qxEZY/74eMG1bdI3z+rq53ORA-----END PKCS7-----"
      title: Verifiable Credential
      properties:
        "@context":
          type: array
          description: The @context property ensures that two systems operating on the same DID document are using mutually agreed terminology. It can be one or more URIs.
          items:
            type: string
        id:
          type: string
          description: Credential identifier.
        type:
          type: array
          description: This array contains the type and subtypes of credential.
          items:
            type: string
        issuanceDate:
          type: string
          description: Date and time at which the information associated with the verifiable credential/presentation becomes valid.
          format: date-time
        issuer:
          type: string
          description: Issuer of the verifiable credential. 
        credentialSubject:
          description: W3C Verifiable Credential content. 
          $ref: "#/components/schemas/subject"
        proof:
          $ref: "#/components/schemas/embeddedProof"
      required:
        - "@context"
        - id
        - type
        - issuanceDate
        - issuer
        - credentialSubject
        - proof
    subject:
      title: Subject
      type: object
      description: A thing about which claims are made
      properties:
        id:
          type: string
          description: "Object MAY contain an id"
          example: "did:example:ebfeb1f712ebc6f1c276e12ec21"
      example:
        Diploma:
          id: "did:example:ebfeb1f712ebc6f1c276e12ec21"
          degree:
            type: BachelorDegree
            name: Bachelor of Science and Arts
        Affiliation:
          id: "did:example:c276e12ec21ebfeb1f712ebc6f1"
          name: Morgan Doe
          spouse: "did:example:ebfeb1f712ebc6f1c276e12ec21"
        ESSIF eID:
          id: "did:ethr:evas-did"
          personIdentifier: BE/BE/02635542Y
          currentFamilyName: Eva
          currentGivenName: Adams
          birthName: Eva
          dateOfBirth: "1998-02-14"
          placeOfBirth: Brussels
          currentAddress: "44, rue de Fame"
          gender: Female
    embeddedProof:
      title: Embedded Proof
      type: object
      description: "Cryptographic proofs that can be used to detect tampering and verify the authorship of a credential or presentation. An embedded proof is a mechanism where the proof is included in the data, such as a Linked Data Signature."
      properties:
        type:
          type: string
          description: Type of the object or the datatype of the typed value.
          example: EcdsaSecp256k1Signature2019
        created:
          type: string
          description: Date and time at which proof has been created.
          format: date-time
          example: "2019-11-17T09:00:00Z"
        proofPurpose:
          type: string
          description: It expresses the purpose of the proof and ensures the information is protected by the signature.
          example: assertionMethod
        verificationMethod:
          type: string
          description: "Specifies the public key that can be used to verify the digital signature. Dereferencing a public key URL reveals information about the controller of the key, which can be checked against the issuer of the credential."
          example: "did:ethr:0x454253492d52554c45532d4d414c494e41524148#eidasKey"
        jws:
          type: string
          description: JSON Web Signature
          example: eyJhbGciOiJFUzI1NksifQ.eyJzdWIiOiJFQlNJIDIwMTkifQ.oggE3ft3kJYPGGa9eBibpbjgeJXw4fLbVMouVoM2NfcDxsl_UUUIarsS1VpBoYEs7s9cBlc4uC0EbnJCHfVJIw
      required:
        - type
        - created
        - proofPurpose
        - verificationMethod
        - jws
      example:
        Embedded Proof:
          type: RsaSignature2018
          created: "2018-06-18T21:19:10Z"
          proofPurpose: assertionMethod
          verificationMethod: "https://example.com/jdoe/keys/1"
          jws: eyJhbGciOiJQUzI1NiIsImI2NCI..
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    AdesProof:
      description: |
        Ades Proof using an EIDAS QEC and signing with CADES and RSA keys.
      type: object
      properties:
        type:
          description: Type of signature
          type: string
          example: CAdESRSASignature2020
        created:
          description: Creation time
          type: string
          example: "2019-06-22T14:11:44Z"
        proofPurpose:
          description: Purpose of the proof
          type: string
          example: assertionMethod
        verificationMethod:
          description: EIDAS Certificate from QEC
          type: string
          example: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
        cades:
          description: CADES Signature in hexadecimal format
          type: string
          example: 308204c906092a864886f70d010702...266ad9fee3375d8095
      additionalProperties: true
      required:
        - type
        - created
        - proofPurpose
        - verificationMethod
        - cades
      example:
        type: "CAdESRSASignature2020"
        created: "2020-06-22T14:11:44Z"
        proofPurpose: "assertionMethod"
        verificationMethod: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
        cades: 308204c906092a864886f70d010702...266ad9fee3375d8095
    GlobalProof:
      description: |
        General Proof type to admit either AdesProof or Secp256k1 proof
      type: object
      properties:
        type:
          description: Type of signature
          type: string
          example: EcdsaSecp256k1Signature2019
        created:
          description: Creation time
          type: string
          example: "2019-06-22T14:11:44Z"
        proofPurpose:
          description: Purpose of the proof
          type: string
          example: assertionMethod
        verificationMethod:
          description: Verification method
          type: string
          example: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
        jws:
          description: JSON Web Signature
          type: string
          example: eyJ...Wuc
        cades:
          description: CADES Signature in hexadecimal format
          type: string
      additionalProperties: true
      required:
        - type
        - created
        - proofPurpose
        - verificationMethod
      example:
        type: "CAdESRSASignature2020"
        created: "2020-06-22T14:11:44Z"
        proofPurpose: "assertionMethod"
        verificationMethod: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
        cades: 308204c906092a864886f70d010702...266ad9fee3375d8095
    EidasQecInput:
      title: Input EIDAS QEC
      type: object
      description: Input data to associate eIDAS keys with a did
      properties:
        did:
          type: string
          description: DID of EIDAS key owner
          example: did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0
        eidasQec:
          description: P12 file with a QEC to eSeal. RSA is the only keys algorithm currently supported.
          type: string
          format: hexadecimal
          example: 30820a5102010330820a1706092a864886f70d010701a0820a0804820a0430820a00308204b706092a864886f70d010706a08204a8308204a40201003082049d06092a864886f70d010701301c060a2a864886f70d010c0106300e0408aafc004c0e4c0ed20202080080820470bf1b516867a1f611e7bd3b547818e77d477b353586d6806625225910454ca2f4fe6bbf3bcc203538288c445ebbcaa2f5f68d6b0037061bda3426e9219caf16f7cb8ba8802e4ed31178cc3c35c576f5d1d9b8c53bf3199596d14ccd003771126dd117c9dd9ec68d9e691d48adb5dd68fd7a25f5db139dd7081150216433555bdd16429d8278ef6a2e270e0e25b908d56a7bc0662db3170748a3364b776c0ff5da21393b4ee88ff441373bef05e48f0ab71be35f2b7cfe7ff8f614202cf52dd7bbd8aa2a46ba0d1c8633a35ad86584a0bccf0ea001c4d2a01e4851fba954374f65771abcc9e0025c5276b72b0ecfb83711b3d83eaafc8b52d7e47911e2fedc3264eba454a0d55b7fee16a4beed6e975a6d01c6416f78ca194d590bbda398b8e9d61d1c1a01a5b64ead0004f4cbaf29f6ed3946cf059fc69774e23aad31229e1ac7ef268af65cfb069436179bb48b0aa868b00cb004d65b2898ad37f5c71ad2f88344fe90bf4bac23f6b3d8ca6bab188d7b4d4bf29784855d8b7d4de7c44ccf756433bc50758c9ff62cb0d20c6bd2f57411d1bbcc943f9681ecd6e74dcb088438ce03dd17a4828717e36e2920475949e407202f33193000ae0cef427400f4694fc586477e75c01ab0c68c5c2757291cc5c354cc3c2e29703d7d4afd1a32071089fd6ee6010329c588fc747f98b88b0df7ffa5cd1080697eeaf4293a686e53cb447d435783c774237faaa70798290a01bcfe738a3ddebe8f1b25429bcb6c4a06e1f8adcf6fe369f80a39b07fb23985416bcdd78b69613059994eca52875738886e8cabdb81113a83092b31ade747cfaa47b13254e974e96125111225ecf49e5549dbdb0498ebd8b326e7098a7736cd893cddf1bc31884f2f1ab926a05c0437378bb753b3efc74532ba6e7ca9b3ef25193a4ca937b38713a048fb28e697ded8f726ac5017309e3fe2f35b57428ce56d5db1a8ea29b5163a1424233e324d2a7ad672c8ef538c0a582122e45dc7cdde4e8cefb1f7820a29bbd8c2686f7d920ac4ab1d2df86eb530b2e9f7635eda4975477dd87c3f2ac45cdbeb8ec2329501956a418567337adda855e75c22bab6026d7d286a2519b3d73117db8563a0d21064ca6df59829cfc142fe682d71e3642f0103bf538c25ac05eea499fe68fa9397d2b162b93fc39f12e328ee6f8b7db387d67248db9f6a946347c7229d22532b85b9cd8659f2d0b7c709dd4f2821e00d3c25340a1b1681b55f65d1ec9691c4e5d85f3e7ea7128e17e0ee1ea3ed54b3b3c77aa5b87dc0e313c72493ce45dafd7a055bd38db3b4c2297b68ca3592b1a9891ee954f4fe016add4115186979f1a7d841c8a77cbd39b231b13d9993d54074887b4825a8365599192061e6484d8788bd25800cf34f9eaa9fdcc2dfe17263d44a4ad62452f2837b099015ebecb3c511281481bb969d3495ac91178fab38f657ee936451ca025bd9ef75c5d623b68931bb5447d7bb87160bbabc644aaa24726c8b7751d3845289c02372b4cdafddcbfb3ec756a7bd6acb4c875711d713ec71fb4476481f038750df4698028781c700f94f7f4d40922388820851e48c9cfc52284ac2e440a653993082054106092a864886f70d010701a08205320482052e3082052a30820526060b2a864886f70d010c0a0102a08204ee308204ea301c060a2a864886f70d010c0103300e0408f5944b68df3976d802020800048204c8573f12920f129546c7d3b4c87f4a1373e7249380718093b4c900cae2e937ac11b3e4244ced86d36632e0fc1292006653d159f026c6d16c20ea864ecaa91f870e8d3f0105f0ab611be1b38e857ea0c269bc956aa1377117e79f7fe5968992c766ada72f1b360ef9ad7dd86b3c76613ceb25d6d07b2a036cd57d5c1a14a764d61e1b8edd96f065203cd2b84f32d09fc1d2168cc1d06237e393da6a9c420d6a8ae409ffac32c7e86dbe087f3eef5085810beecc60465bb3012e4272534297917a3c8fed8d8aba98c73ffcfae254ab10d2fcd0ddb689c91729510918e619a842d1a22188fb2b824b7f61357b9c654a44aa299535c06748d3adcb083a842f8a13e97e2006cb2d0bbefd8195314d76b8f585cd8e45d558ea8d26aa5a8ab704efe29ef0a9f5cfdeefc70fba1d073363490b00c0dc8145b34e498e131433a6502d582c15b833d3369fd3bec92470665c4e0ace27b18651b098d8611d8618a295298975e6ba160d57dd9c3aba72c24a6fd1d7e08474dfdc3fd74b86d4a9a898c308f7709dc294e6439d7d00e317d6a7389f58f54fb559ef5adbf6986bb38b47f3a95f92a69371d029d584b6afd74109eb95aa05ed9f850307f974060736f2df6f6bbd1fb163664d26b7323acd14ca8acb2a935c4722f9af259506a7d3a4dba72fdb6986e5f940f4496ae51b2f035c400e1dee6fd8c67b22b17f3a945c14e2afd46cadd7e7ac10415e6388b58e65949fe2b6393a36e5c653cbcb4133df4eb2d5abc0d12c5b58ab161da5b850b6c9b2c840052221218b21d42a0da364cda40c66b0fdcf462ebdc924099b05324372ae9d824787f93fc49d81bbc46be964d15310829fdab7a4931717d3df27cde4a07c7e8c12babd97d1e72e7bb08dbc3a57b4c751f4873747f3c2bd37a8ec9fb2bac925e1ded38ac46dd1adf26c0e2ef11ac2b38d45bc335e03a588da1444a283cce13bdcffff19347d175d2d93828588fbf9d16d0b02bf7c44c8bc9bbacdd0b208d44fe05cfdb1a759e7710a23532be5761aa80e7f007dce5d81cfbe8fd4952efc7698582f2ca36f2f80c1def4b47c0a7383ee9afaaddb75abaf0605da9f73e0c50dcc07a92f88e180d216fdbe1437059de21b0ad1aaf9c4369cd2a20614d96cdbc4ac9346c6a7983fe4543b16f50cf97edb7953ae45abd95e4ccf6e335a50f4f82b1fd63a32b89b04c7bc16713b6a351e780bccb60b9fd9b97173c47342e22fd492e16ec980b534dabbc41b44ef58299fe2d5c1434e280342b87443591415a55f6daf81921c29b0db385899bf9d3c045b5d2942d24100ae8da592523acd5068c49a9413984c3b1a3fcbf2c566d3d503909a028d334ef62851ef277b5c1d100362dc6057631d089fbb0ecc97ae425deb7f7808049b96c15f4e1dd9ee84733bdadd3e4f5a08639904273b5fa62bc90c39a41afbdfb455940155be660bf754388e6d1d587fb4cc6f496ae30459817ead77f68007ad7c6acd5caed7e43ba7a53ae914e1d7e01258f4068585c0ce8848828b49e0cbbeac313d605e829d42ae2b26bc7060d73cdd52d5edd4ab3bce2f20b27d0420b3a2581a3ef0d183417d21b15dc1ed1f7e73daa9170537f39137b0e5708d5c318c0ae8d8a7f87e0ea5d710ed2fbe2c83651464cc06723d9173d04253809650e4e3061422f012dc177ecb2f5ae78b8df625beed63220bfaacb403c9582a15c5b884dba3f995836a190c4f647387813125302306092a864886f70d010915311604143dbf08c4e60fd8fc0a49027923588c40dc0c980530313021300906052b0e03021a05000414f0d4509827c3f98b115a469a0eb538938ebc188804085f332df8eaadeedc02020800
      required:
        - did
        - eidasQec
    EidasQecResponse:
      title: EidasQecResponse
      type: object
      description: Response for a sucessful eIDAS keys set-up.
      properties:
        id:
          type: string
          description: DID of EIDAS key owner
          example: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
      example:
        id: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
    SignatureInput:
      title: Signature EIDAS Input
      type: object
      description: Input data to eSeal a given Credential or Verifiable Credential
      properties:
        issuer:
          description: DID of the Issuer
          type: string
          example: did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0
        payload:
          description: W3C Verifiable Credential or Credential (without Proof) to eSeal
          type: object
          example:
            "@context":
              - "https://www.w3.org/2018/credentials/v1"
            id: "https://example.com/credential/2390"
            type:
              - VerifiableCredential
              - VerifiableId
            issuer: "did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0"
            issuanceDate: "2022-06-09T12:42:48.000Z"
            credentialSubject:
              birthName: "Eva"
              currentAddress: "44, rue de Fame"
              currentFamilyName: "Eva"
              currentGivenName: "Adams"
              dateOfBirth: "1998-02-14"
              gender: "Female"
              id: "did:ethr:0x2Bb1629Dc1f992E00a9E170464BE3802ba259B3E"
              personIdentifier: "BE/BE/02635542Y"
              placeOfBirth: "Brussels"
            proof:
              type: "EcdsaSecp256k1Signature2019"
              created: "2022-06-09T12:42:48.000Z"
              proofPurpose: "assertionMethod"
              verificationMethod: "did:ethr:0xDfBA7E7D6fd9D3B5B900cE2aa3d9E6aA43574FC0#keys-1"
              jws: "eyJhbGciOiJFUzI1NksiLCJraWQiOiJkaWQ6ZXRocjoweERmQkE3RTdENmZkOUQzQjVCOTAwY0UyYWEzZDlFNmFBNDM1NzRGQzAja2V5cy0xIiwidHlwIjoiSldUIn0.eyJpYXQiOjE2NTQ3Nzg1NjgsImlzcyI6ImRpZDpldGhyOjB4RGZCQTdFN0Q2ZmQ5RDNCNUI5MDBjRTJhYTNkOUU2YUE0MzU3NEZDMCIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImJpcnRoTmFtZSI6IkV2YSIsImN1cnJlbnRBZGRyZXNzIjoiNDQsIHJ1ZSBkZSBGYW1lIiwiY3VycmVudEZhbWlseU5hbWUiOiJFdmEiLCJjdXJyZW50R2l2ZW5OYW1lIjoiQWRhbXMiLCJkYXRlT2ZCaXJ0aCI6IjE5OTgtMDItMTQiLCJnZW5kZXIiOiJGZW1hbGUiLCJpZCI6ImRpZDpldGhyOjB4MkJiMTYyOURjMWY5OTJFMDBhOUUxNzA0NjRCRTM4MDJiYTI1OUIzRSIsInBlcnNvbklkZW50aWZpZXIiOiJCRS9CRS8wMjYzNTU0MlkiLCJwbGFjZU9mQmlydGgiOiJCcnVzc2VscyJ9LCJpZCI6Imh0dHBzOi8vZXhhbXBsZS5jb20vY3JlZGVudGlhbC8yMzkwIiwiaXNzdWVyIjoiZGlkOmV0aHI6MHhDQzI0MkEzZGNBMzkzNjM4NDc2MDdjOTg5ZDVhMzNDMmY2RDZhMEZmIiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZlcmlmaWFibGVJZCJdfX0.XfY8VdEInTadbUo8MAimW6CbvLWxGgDuMk1W5f24ynCzJaZG8K6MjXDsy16WLjiXonkUwtRTfdnI5k_Oic5U5g"
        password:
          description: Password to decode P12 file
          type: string
          format: password
          example: testpassword
        expiresIn:
          description: expiration time in seconds
          type: number
          example: 86400
      required:
        - issuer
        - payload
    verifiableCredentialEsealed:
      type: object
      title: Signature Response
      properties:
        id:
          type: string
          example: "https://example.edu/credentials/1872"
          description: "URI that is used to unambiguously refer to an object, such as a person, product, or organization."
          format: uri
        "@context":
          description: "An ordered set where the first item is a URI https://www.w3.org/2018/credentials/v1. It is used to define terms and help to express specific identifiers in a compact manner."
          items:
            type: string
          uniqueItems: true
          example:
            - "https://www.w3.org/2018/credentials/v1"
          type: array
        type:
          type: array
          description: Type of the object or the datatype of the typed value.
          example:
            - VerifiableCredential
            - UniversityDegreeCredential
          items:
            type: string
        issuer:
          description: "A URI or an object containing an id property. Example: DID of the verifiable credential/presentation issuer."
          oneOf:
            - type: string
              description: DID of the verifiable credential/presentation issuer.
              format: uri
              example: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
            - type: object
              description: Object containing an id property to identify the issuer.
              properties:
                id:
                  type: string
                  description: "URI that is used to unambiguously refer to an object, such as a person, product, or organization."
                  format: uri
                  example: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
        credentialSubject:
          description: A set of objects that contain one or more properties that are each related to the subject of the credential.
          type: object
          oneOf:
            - $ref: "#/components/schemas/subject"
            - type: array
              uniqueItems: true
              items:
                $ref: "#/components/schemas/subject"
        issuanceDate:
          type: string
          description: Date and time at which the information associated with the verifiable credential/presentation becomes valid.
          format: date-time
          example: "2010-01-01T19:23:24Z"
        expirationDate:
          type: string
          format: date-time
          example: "2020-01-01T19:23:24Z"
          description: Date and time at which a credential/presentation ceases to be valid.
        proof:
          type: object
          oneOf:
            - $ref: "#/components/schemas/AdesProof"
            - type: array
              uniqueItems: true
              items:
                $ref: "#/components/schemas/GlobalProof"
      example:
        "@context":
          - "https://www.w3.org/2018/credentials/v1"
          - "https://api.vidchain.net/credentials/verifiableId/v1"
        id: "http://example.gov/credentials/3732"
        type: "['VerifiableCredential','VerifiableID']"
        issuer: did:key:zQ3shokFTS3brHcDQrn82RUDfCZESWL1ZdCEJwekUDPQiYBme
        issuanceDate: "2019-06-22T14:11:44Z"
        expirationDate: "2019-06-22T14:11:44Z"
        credentialSubject:
          id: did:key:zQ3shtxV1FrJfhqE1dvxYRcCknWNjHc3c5X1y3ZSoPDi2aur2
          firstName: "Eva"
          lastName: "Monroe"
          gender: "Female"
          dateOfBirth: "12/11/1970"
          placeOfBirth: "Madrid"
          currentAddress: "Arago 179 4a"
          city: "Barcelona"
          state: "Catalunya"
          zip: "08011"
        proof:
          type: "CAdESRSASignature2020"
          created: "2020-06-22T14:11:44Z"
          proofPurpose: "assertionMethod"
          verificationMethod: did:key:z6MkfGYwYV8xQgoNtyFgxdHLuBC6vzSCoHUKpeUg5uBvkXLE#MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvcPOS736aX2tfwEj+mMCJ3kw6KBCDHLRNqtkDseXNTuhdIs5Uj7wPcOETexT1DnGDfPZ3HYBsc8x8jWKFtO/E5oqFzXDyq60G8Qmlt509JKQJLP0YxrXwjZcLD/uM9Qf8lCjjiVJjDYnztE88p5jkQ2V9HCf3NK3ASL3m2q4M5QRHNGiTTvCvcRG2qRocVIp3EB8fwIpgqWxi6uI242yE7E1J4fVDXlD4hYpocDH0HOzazQXrNubHz6EGkOt5nAKeEzToqE9ow++h6TRHhfmdWJFb2HQ7FvoAMUYopQJaKpk/V5FpmXTDyMPNt2uj9UBS/EML7Z3vXzXUUJq/pTbdtJIpZaZk0SOCdt3iWk8CCNIHAHdN0uy+SWC+AH0hv56urQqR0Zaz33fGguhbuUYKzXt1CTQgCTkEhcwT9Sml4m1WGMl3fbFMFkacPGRwSMs5ZXKjDCRdz+N8/pFExOuobCqIMUPGC98TVsV3drrsSe716CSHS3BWuaum/W3ve5w1Z11nGbRih9X5AuYg5t/gwFDsg05iQa76ymzWSaZEEL5btHvCXNsmsyDU1n/KJw4S8nnXj+qt+xLNENNWsijcP7VnE1bkXvEQ0rg/PewmPWKVLIHZf5s8RJTmAdCFE0IJT1WiXufwT9QUa6BfyE1mOpnk4LpwkhcmM0jNADHvp8CAwEAAQ==
          cades: 308204c906092a864886f70d010702...266ad9fee3375d8095
      required:
        - "@context"
        - type
        - proof
    Verification:
      title: Verification result
      description: Result for Signature Verification
      type: object
      properties:
        indication:
          description: Descriptor of the result obtained
          type: string
          enum:
            - TOTAL_PASSED
            - TOTAL_FAILED
            - INDETERMINATE
          example: TOTAL_PASSED
        checks:
          description: String list
          type: array
          items:
            type: string
          example:
            - credential
            - proof
        warnings:
          description: String list
          type: array
          items:
            type: string
        errors:
          description: String list
          type: array
          items:
            type: string

  examples:
    EntitySessionRequest:
      value:
        grantType: urn:ietf:params:oauth:grant-type:jwt-bearer
        assertion: ewogICAgImlzcyI6ImVudGl0YXRTd2FnZ2VyIiwKICAgImF1ZCI6InZpZGNoYWluLWFwaSIsCiAgICJub25jZSI6InotMDQyN2RjMjUxNWIxIiwKICAgImNhbGxiYWNrVXJsIjoiaHR0cDovLzEyNy4wLjAuMTo4MDgwL2RlbW8vZW50aXRhdC1leGVtcGxlL2NhbGxiYWNrIiwKICAgImFwaUtleSI6ICI2MDAxMGMwZi05MmQ2LTQyMDYtYmFjYi1hMDRhYzA4MGVjNjMiCn0=
        scope: vidchain profile entity
        expiresIn: 2592000
    UserSessionRequest:
      description: In case of **User Session Request**, the assertion has to be a **JWT token** signed with User's DID private key
      value:
        grantType: urn:ietf:params:oauth:grant-type:jwt-bearer
        assertion: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE2MjMwNjQzNzAsImF1ZCI6InZpZGNoYWluLWFwaSIsImV4cCI6NDg5NTg0Mjc1NjksInB1YmxpY0tleSI6IjB4MDQ2NGFkNjA1ZmRkMjU2ODk2YTNkN2IwOTA0ZTEzN2U2NjdlOGY5ZmQ5OGY0NDg1MjFlMWE4ZWU5ZjRiYzBkOWM1M2VmN2IwMDYyYWQ5ZjRkZDQ3Y2U2MTRiZWJkZTBlN2FmMTIzMTgzYThjZTRiMmE5NTAwYzc2ZmRhNTdmZDZlOCIsImZjbVRva2VuIjoiZENiMTF3ejVSTTZsLXdDOThSemlCTzpBUEE5MWJGMEs0LWVDQjJYaUQzQV9QNWUxNWY1Ni1SRTk2MkJHOGFZRENSUzBUU1FVbFUyRUJOdHRoakVQRkgxajdFVjRQcUxpWmZya0locDM5WFdsU3ZsZlJ4b0MtUnJlNzVkN2hzSU5VRHNKOHlfOVRDN1JpMnZyU05nV0FxdURhY09KMTJVaF9jTSIsImlzcyI6ImRpZDp2aWQ6MHg2MDM5NTQ0NGM5RDUyYkExRWRlNDZGNDY1OGZjM2QwRUY0NTdCM2Q5In0.EcMFzMgn6myyidvxBePMtVuHXZvux5qnalUBIQ1StuBDEAbshVqULd9ighxi8QpZXWwqaszf54fTpmudJSPceAE
        scope: vidchain profile user
        expiresIn: 2592000
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request.
    Unauthorized:
      value:
        title: Unauthorized
        status: 401
        detail: Permission denied.
    Forbidden:
      value:
        title: Forbidden
        status: 403
        detail: "Forbidden You don't have the right to access that ressource"
    ExpiredToken:
      value:
        title: Token Expired
        status: 400
        detail: The token has expired.
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: The server encountered an internal error and was unable to complete your request.
    TotalSuccess:
      value:
        indication: "TOTAL_PASSED"
        checks:
          - "credential"
          - "proof"
        warnings:
          - ""
        errors:
          - ""
    TotalFailed:
      value:
        indication: "TOTAL_FAILED"
        checks:
          - "credential"
          - "proof"
        warnings:
          - ""
        errors:
          - "Error message information"
    Indeterminate:
      value:
        indication: "INDETERMINATE"
        checks:
          - "credential"
          - "proof"
        warnings:
          - ""
        errors:
          - "Error message information"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
